### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by hawwjla** [SandhyR/Neutron#5]
C:\Users\ASUS\Desktop\Neutron>go run main.go
Authenticate at https://www.microsoft.com/link using the code E85H3S6F.
Authentication successful.
2022/06/08 21:15:03 Listening on 0.0.0.0:19132
2022/06/08 21:15:24 error: server outdated
panic: dial minecraft 192.168.1.3:54835->192.53.113.9:19132: use of closed network connection

goroutine 29 [running]:
main.handleConn(0xc0000e4000, 0xc0000bc3c0, {{{0xc000020c10, 0xd}, {0xc00001e300, 0x12}}, {{0x0, 0x0}, 0x0}}, {0xfda1e0, ...})
        C:/Users/ASUS/Desktop/Neutron/main.go:67 +0x42d
created by main.main
        C:/Users/ASUS/Desktop/Neutron/main.go:53 +0x310
exit status 2

C:\Users\ASUS\Desktop\Neutron>
C:\Users\ASUS\Desktop\Neutron>
C:\Users\ASUS\Desktop\Neutron>hhe
'hhe' is not recognized as an internal or external command,
operable program or batch file.

**Comment by SandhyR** [comment]
Thats because outdated server
