### ISSUE TITLE
Error on kontol

### ISSUE THREAD

**Issue by ProtectorYT364** [SandhyR/Neutron#6]
panic: dial minecraft: error obtaining XBOX Live token: POST https://device.auth.xboxlive.com/device/authenticate: Post "https://device.auth.xboxlive.com/device/authenticate": dial tcp: lookup device.auth.xboxlive.com: No address associated with hostname

goroutine 341 [running]:
main.handleConn(0x4000148f00, 0x4000127040, {{{0x400002c510, 0xd}, {0x4000028140, 0x13}}, {{0x0, 0x0}, 0x0}}, {0x5d5855f7e0?, ...})
        /data/data/com.termux/files/home/Neutron/main.go:67 +0x314
created by main.main
        /data/data/com.termux/files/home/Neutron/main.go:53 +0x284
exit status 2

**Comment by SandhyR** [comment]
haram issue
